customhost = "database-manis1.c54nh4jkdu0t.us-east-2.rds.amazonaws.com"
customuser = "adm_mani83"
custompass = "shalimar145"
customdb = "maninder_db1"
custombucket = "addmyspace"
customregion = "us-east-2"